name: clean_test
description: A Dart package for writing clean unit tests.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: ^1.8.0
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
